### ISSUE TITLE
Extraction folder always deleted, CP re-downloaded and re-unzipped

### ISSUE THREAD

**Issue by andylwelch** [HCL-TECH-SOFTWARE/connections-automation#119]
Sometimes you need to run the ansible task a few times to get things right. At the moment the Component Pack is always deleted at the start, re-downloaded, and re-unzipped.

Could we please have a variable to disable these tasks in order for us to re-use the existing valid files that we already have?

**Comment by dejo1307** [comment]
Hi Andrew,

I think this is already solved.

Check this out: https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/10bc3447bf802622be471bf92fb87bd7a87d0968/environments/examples/cnx7/db2/group_vars/all.yml#L80-L81

Add setup_installation: false and it will skip downloading, unzipping, cleaning, etc. Add setup_images: false and it will skip trying to reupload images and wasting time on that. 

All those variables: https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/10bc3447bf802622be471bf92fb87bd7a87d0968/environments/examples/cnx7/db2/group_vars/all.yml#L80-L101 are intended to give you exactly the chance to skip one or most of the steps and to execute just the one you need. 

Is this what you need?

And yeah, they are not visible in quick start example, since quick start is just a bare minimum there. I can expose their defaults there too, but there were some opinions where people didn't want it as it was confusing them, but just a minute to add it if it would help others too.

**Comment by andylwelch** [comment]
Thanks for the reply. Yes, those variables should do the job.
