### ISSUE TITLE
Hardcoded nfs folders

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#155]
Hi

I use one NFS Server for multiple connections test deployments, but there are some issues:

- The /etc/exports file gets overwritten within several playbooks
- there are several parts with hard coded paths: for example https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/c9297a53dab06ea1d822952c4605419251f453f1/roles/hcl/connections/vars/main.yml#L44
- if I don't use the default paths, the folders are not created on the filesystem and added to /etc/exports automatically

Regards
Christoph

**Comment by stoeps13** [comment]
Additionally the nfs roles are using the wrong paths:

`roles/third_party/nfs-install/vars/main.yml:__cnx_data_shared:                   "{{ cnx_shared_area | default('/nfs/data/shared') }}"
roles/third_party/nfs-install/vars/main.yml:__cnx_message_stores:                "{{ cnx_message_store | default('/nfs/data/messageStores') }}"
roles/third_party/nfs-install/vars/main.yml:__docs_data_shared:                  "{{ docs_data_shared | default('/nfs/docs_data') }}"
roles/third_party/nfs-install/vars/main.yml:__viewer_data_shared:                "{{ viewer_data_shared | default('/nfs/viewer_data') }}"`

When I compare this with the environment files, thate the defaults need to point to the *_data_remote_paths!

**Comment by nitinjagjivan** [comment]
Thanks @stoeps13 for your valuable inputs. My observations are as below:

1. For 'The /etc/exports file gets overwritten within several playbooks'
A- The /etc/exports file is updated only when user is configuring NFS master in below file - 
roles/third_party/nfs-install/tasks/configure_master.yml

This may happen twice (with same file content unless inventory is updated) - first while installing connections and second while installing component pack, which is needed. 

2. For 'there are several parts with hard coded paths: for example '
A- Yes agree with you. We in process of changing it to use an existing variable instead of hard coded paths as below - 
roles/hcl/connections/vars/main.yml:
__cnx_message_store_nfs: "{{ cnx_message_store_nfs | default('/nfs/data/messageStores') }}"
__cnx_shared_area_nfs:       "{{ cnx_shared_area_nfs | default('/nfs/data/shared') }}"

We will be using cnx_message_store_nfs  and cnx_shared_area_nfs as these are existing variables used in other roles as well.

3. For 'Additionally the nfs roles are using the wrong paths:':
A- Agree, defaults are pointing to the NFS master. Actually these variables here are used to setup NFS master node so defaults look good. Instead we need to change nfs master path variables as below - 
roles/third_party/nfs-install/vars/main.yml:__cnx_data_shared:                   "{{ cnx_shared_area_nfs | default('/nfs/data/shared') }}"
roles/third_party/nfs-install/vars/main.yml:__cnx_message_stores:                "{{ cnx_message_store_nfs | default('/nfs/data/messageStores') }}"
roles/third_party/nfs-install/vars/main.yml:__docs_data_shared:                  "{{ docs_data_remote_path | default('/nfs/docs_data') }}"
roles/third_party/nfs-install/vars/main.yml:__viewer_data_shared:                "{{ viewer_data_remote_path | default('/nfs/viewer_data')

4. For 'if I don't use the default paths, the folders are not created on the filesystem and added to /etc/exports automatically'
A- I assume issue will be resolved after fixing all above points. I am testing the same on my local.
I added below vars in my inventory file- 
cnx_message_store_nfs:                           /nfs/data/messageStores123
cnx_shared_area_nfs:                             /nfs/data/shared123
cnx_message_store:                               /opt/HCL/MessageStore123
cnx_shared_area:                                 /opt/IBM/SharedArea123

After running NFS setup, following entries can be seen in /etc/exports:
/nfs/data/shared123        172.27.1.0/255.255.255.0(insecure,rw,async,no_root_squash)
/nfs/data/messageStores123       172.27.1.0/255.255.255.0(insecure,rw,async,no_root_squash)

Folder created:
[xxxxxx ~]$ ls /nfs/data/
messageStores123  shared123

Let me know if you agree with this. We will create a PR soon with these changes.

**Comment by stoeps13** [comment]
Hi @nitinjagjivan 
I worked on this yesterday and created following PR https://github.com/HCL-TECH-SOFTWARE/connections-automation/pull/160

I think the hardcoded nfs and not using remote_path variables were the main issues. With this PR I was able to use custom folders on NFS. Haven't checked multiple environments with one NFS now, but that's not that important for me.
Regards
Christoph

**Comment by nitinjagjivan** [comment]
Hi @stoeps13,
You are using 'cnx_message_store_remote_path' which is a new variable. Instead we can use an existing variable 'cnx_message_store_nfs' which is used in other tasks as well. 
Similarly 'cnx_data_remote_path' is used mostly for Docs installation. So instead we can use an existing variable 'cnx_shared_area_nfs'.

I will raise a PR with all the details discussed above.
Thanks again for highlighting these issues.

**Comment by stoeps13** [comment]
I just replaced the hardcoded value with a variablename which looked similar to the others.

If it works feel free to rename it.

**Comment by stoeps13** [comment]
I think this is solved, so I close it.
