### ISSUE TITLE
Kubernetes 1.24: kubeadmin config wrong api version

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#221]
kubeadmin 1.24+ uses `apiVersion: kubeadm.k8s.io/v1beta3` instead of `apiVersion: kubeadm.k8s.io/v1beta2` 

So the ` kubeadmin init fails`

**Comment by sabrina-yee** [comment]
@stoeps13 what is the Kubernetes version set in your all.yml for `kubernetes_version`?  We use `1.24.1` as the default so want to use what you set to attempt to reproduce the issue.  Thanks.

**Comment by stoeps13** [comment]
@sabrina-yee I haven't set a version, it uses the default 1.24.1

I tried manually with the generated config.yaml it shows wrong api version.

**Comment by sabrina-yee** [comment]
@stoeps13 we ran into this issue today along with issue #223.  The problem in our case is that containerd was installed as part of docker (via the `setup-docker-registry.yml` playbook) rather than using `setup-containerd.yml` from `setup-component-pack-complete-harbor.yml`.  The docker one creates a different `/etc/containerd/config.toml` with this line in it:

`﻿disabled_plugins = ["cri"]`

that leads to `[ERROR CRI]: container runtime is not running`.  Commenting out this line will address both this issue and #223.

**Comment by stoeps13** [comment]
Hi Sabrina,
I found the issue too. There is a new playbook named https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/main/playbooks/setup-component-pack-complete-harbor.yml, I did the first try with the old playbook which fails with the described errors.
Regards
Christoph
