### ISSUE TITLE
Add variable for database selection

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#70]
Hi,

in the actual version the playbook setup_database.yml installs both database systems (DB2 and Oracle)! So a variable to select the used database would help.

Keep up the great work.

Regards
Christoph

**Comment by dejo1307** [comment]
Hey @stoeps13 - I intentionally didn't add it - because yes, that playbook will install actually the one which is defined in inventory file - if you define oracle_servers, it will be Oracle, db2_servers for DB2, check out how modules are implemented (and same is coming for MSSQL as well).
I just tried to create one variable less; however, there are different playbooks for db2 and/or oracle, and it is easy to create also another playbook, just trying not to end up with 100 playbooks with super long names explaining different mappings :))
Saying this - is something broken?

**Comment by stoeps13** [comment]
I used the default install_connections playbook, which includes install_database.yml. I have no oracle_servers in inventory and it starts downloading oracle. (Which is not in the downloads). So something is missing, but Ii haven't looked into it to be honest. Just changed the playbook to include only DB2.

**Comment by dejo1307** [comment]
Got you, that's definitely the bug. Let me check it out, I think I know where that one comes from.

**Comment by stoeps13** [comment]
I rerun the playbook multiple times and it downloads for example the db2 installer on each run and extract it.

I can understand this to fix errors, but from an idempotent approach, it needs a lot of time and changes files which are already applied (repsonse files).
